version: "3"
services:
  ark:
    container_name: ark
    image: paulknisely/arkmanager-docker
    environment:
    - SESSIONNAME=Ark Docker
    - SERVERMAP=TheIsland
    - SERVERPASSWORD=""
    - ADMINPASSWORD=adminpassword
      - BACKUPONSTART=1
      - UPDATEONSTART=1
      - TZ=Asia/Tokyo
      - GID=1000
      - UID=1000
    volumes:
      - /var/ark:/ark
    ports:
      - 7778:7778/udp
      - 7778:7778
      - 27015:27015/udp
      - 27015:27015
      - 32330:32330
